version: "3.9"

services:
  ccm_db:
    image: mysql:latest
    container_name: ccm_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ccm
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
